[tool.poetry]
name = "bibliotheque"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0.2"
psycopg2 = "^2.9.3"
loguru = "^0.6.0"
requests = "^2.27.1"
pandas = "^1.4.2"
bs4 = "^0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
