# Generated by Django 4.0.2 on 2022-11-12 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'author',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('lastname'), nulls_last=True), django.db.models.expressions.OrderBy(django.db.models.expressions.F('firstname'), nulls_last=True), 'id'],
                'get_latest_by': 'id',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('is_ebook', models.IntegerField(blank=True, null=True)),
                ('book_type', models.IntegerField(blank=True, choices=[(0, 'Roman'), (1, 'Documentaire'), (2, 'Manga'), (3, 'Théâtre'), (4, 'Poésie')], null=True)),
                ('series', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('reading_state', models.CharField(choices=[('read', 'Lu'), ('reading', 'Lecture en cours'), ('to be read', 'Prochaine lecture')], default=('read', 'Lu'), max_length=150)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('date_end_reading', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book',
                'ordering': ['title', django.db.models.expressions.OrderBy(django.db.models.expressions.F('series'), nulls_last=True)],
                'get_latest_by': 'date_end_reading',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WrittenBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookshelv.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bookshelv.book')),
            ],
            options={
                'db_table': 'written_by',
                'get_latest_by': 'book_id',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='writtenby',
            constraint=models.UniqueConstraint(fields=('author_id', 'book_id'), name='unique_book_id_author_id_combination'),
        ),
    ]
