# Generated by Django 4.1.3 on 2022-11-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelv", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "get_latest_by": "date_end_reading",
                "managed": True,
                "ordering": ["title", "series"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="progression",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="reading_state",
            field=models.CharField(
                choices=[
                    ("read", "Lu"),
                    ("reading", "Lecture en cours"),
                    ("to be read", "Prochaine lecture"),
                ],
                default="read",
                max_length=150,
            ),
        ),
    ]
